// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcdfephraaiusolzfdvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZGZlcGhyYWFpdXNvbHpmZHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjU4MTgsImV4cCI6MjA3MDk0MTgxOH0.9Tsm4sNTIy2AX9--y28rWjHkwD8OAiddm2NxHCZdDd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});